nordiclens:
  target: prod
  outputs:
    prod:
      type: snowflake
      account:   "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user:      "{{ env_var('SNOWFLAKE_USER') }}"
      password:  "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role:      "{{ env_var('SNOWFLAKE_ROLE',      'NORDICLENS_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'NORDICLENS_WH') }}"
      database:  "{{ env_var('SNOWFLAKE_DATABASE',  'NORDICLENS_DB') }}"
      schema:    STAGING   # dbt overrides per model via +schema config
      threads:   4
      client_session_keep_alive: false
